// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: book_query.sql

package sqlc_gen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateBooksParams struct {
	Title         string
	AuthorID      int64
	PublishedDate pgtype.Date
}
