// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package sqlc_gen

import (
	"context"
)

// iteratorForCreateBooks implements pgx.CopyFromSource.
type iteratorForCreateBooks struct {
	rows                 []CreateBooksParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBooks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBooks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Title,
		r.rows[0].AuthorID,
		r.rows[0].PublishedDate,
	}, nil
}

func (r iteratorForCreateBooks) Err() error {
	return nil
}

func (q *Queries) CreateBooks(ctx context.Context, arg []CreateBooksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"books"}, []string{"title", "author_id", "published_date"}, &iteratorForCreateBooks{rows: arg})
}
