/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaprojectdemo;
import javaprojectdemo.dao.UserDao;
import javaprojectdemo.model.User;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Add new user
        User user = new User();
        user.setUsername("fast");
        user.setPassword("secret");
        user.setFullName("test test");
        user.setEmail("test@test.com");
        // Update user
        System.out.println("Adding data to the database");
        UserDao dao = new UserDao();
        dao.addUser(user);
        user.setPassword("verysecret");
        dao.updateUser(user);
    }
}
