/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaprojectdemo;
import javaprojectdemo.dao.UserDao;
import javaprojectdemo.model.User;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Add new user
        User user = new User();
        user.setUsername("luiz");
        user.setPassword("secret");
        user.setFullName("Luiz Suarez");
        user.setEmail("luiz@example.com");
        // Update user
        UserDao dao = new UserDao();
        dao.addUser(user);
        user.setPassword("verysecret");
        dao.updateUser(user);
        System.out.println(dao.getAllUsers());
    }
}
