openapi: 3.0.3
info:
  title: User Service
  version: 1.0.0
  description: API for managing users

servers:
  - url: http://localhost:8080

tags:
  - name: Users

paths:
  /users:
    $ref: "./paths/users.yaml"

components:
  schemas:
    $ref: "./components/schemas.yaml"
